exclude: null
grid-search:
  
  opponent_model_decode_observations:
    - true
    - false
  
  opponent_model_decode_actions:
    - true
    - false
  
  opponent_model_decode_rewards:
    - false
  
  opponent_modelling:
    - true


grid-search-groups:
  env1:
    - "--env-config": "smaclite"
    - env_args.map_name: "MMM2"
    - common_reward: True
    - t_max: 5050000
    - test_interval: 125000
    - log_interval: 100000
    - save_model_interval: 2500000
    - latent_dims: 32
    - "--config": "mappo"
  
  env4:
    - "--env-config": "smaclite"
    - env_args.map_name: "10m_vs_11m"
    - common_reward: True
    - t_max: 5050000
    - test_interval: 125000
    - log_interval: 100000
    - save_model_interval: 2500000
    - latent_dims: 32
    - "--config": "mappo"