exclude: null
grid-search:

  save_model:
    - true

  opponent_modelling:
    - true
  
  opponent_model_decode_observations:
    - true
    - false
  
  opponent_model_decode_actions:
    - true
    - false
  
  opponent_model_decode_rewards:
    - true
    - false
  
  latent_dims:
    - 5
    - 10
    - 32


grid-search-groups:
  env0:
    - "--env-config": "gymma"
    - env_args.time_limit: 25
    - env_args.key: "pz-mpe-simple-spread-v3"
    - common_reward: False
    - t_max: 10050000
    - test_interval: 250000
    - log_interval: 100000
    - save_model_interval: 5000000
    - "--config": "mappo"