exclude: null
grid-search:

  save_model:
    - true

  opponent_modelling:
    - true
    - false


grid-search-groups:
  env1:
    - "--env-config": "gymma"
    - env_args.time_limit: 50
    - env_args.key: "lbforaging:Foraging-4s-20x20-2p-4f-v3"
    - common_reward: False
    - t_max: 15050000
    - test_interval: 250000
    - log_interval: 100000
    - save_model_interval: 5000000
    - opponent_model_decode_observations: True
    - opponent_model_decode_rewards: False
    - opponent_model_decode_actions: False
    - latent_dims: 32
    - "--config": "mappo"