exclude: null
grid-search:

  save_model:
    - true

  opponent_modelling:
    - true
  
  opponent_model_decode_observations:
    - false
  
  opponent_model_decode_actions:
    - true
  
  opponent_model_decode_rewards:
    - false
  
  latent_dims:
    - 0
    - 1
    - 5
    - 10
    - 32
    - 64


grid-search-groups:
  env0:
    - "--env-config": "smaclite"
    - env_args.map_name: "MMM2"
    - common_reward: True
    - t_max: 5050000
    - test_interval: 125000
    - log_interval: 100000
    - save_model_interval: 2500000
    - "--config": "mappo"