exclude: null
grid-search:
  
  opponent_model_decode_observations:
    - true
    - false
  
  opponent_model_decode_actions:
    - true
    - false
  
  opponent_model_decode_rewards:
    - true
    - false


grid-search-groups:
  env0:
    - "--env-config": "gymma"
    - env_args.time_limit: 25
    - env_args.key: "pz-mpe-simple-spread-v3"
    - common_reward: False
    - t_max: 10050000
    - opponent_modelling: True
    - save_model: True
    - test_interval: 250000
    - log_interval: 100000
    - latent_dims: 32
    - save_model_interval: 5000000
    - "--config": "mappo"