exclude: null
grid-search:
  
  opponent_model_decode_observations:
    - true
  
  opponent_model_decode_actions:
    - true
  
  opponent_model_decode_rewards:
    - false
  
  latent_dims:
    - 0
    - 1
    - 5
    - 10
    - 32
    - 64


grid-search-groups:
  env0:
    - "--env-config": "gymma"
    - env_args.time_limit: 50
    - env_args.key: "lbforaging:Foraging-10x10-4p-4f-v3"
    - common_reward: False
    - opponent_modelling: True
    - save_model: True
    - t_max: 10050000
    - test_interval: 250000
    - log_interval: 100000
    - save_model_interval: 5000000
    - latent_dims: 32
    - "--config": "mappo"