exclude: null
grid-search:

  save_model:
    - true

  opponent_modelling:
    - true
    - false


grid-search-groups:
  env1:
    - "--env-config": "gymma"
    - env_args.time_limit: 50
    - env_args.key: "lbforaging:Foraging-2s-15x15-3p-4f-v3"
    - common_reward: False
    - t_max: 20050000
    - test_interval: 250000
    - log_interval: 100000
    - save_model_interval: 5000000
    - opponent_model_decode_observations: False
    - opponent_model_decode_rewards: False
    - opponent_model_decode_actions: True
    - latent_dims: 32
    - "--config": "mappo"
  
  env2:
    - "--env-config": "smaclite"
    - env_args.map_name: "MMM2"
    - common_reward: True
    - t_max: 5050000
    - test_interval: 125000
    - log_interval: 100000
    - save_model_interval: 2500000
    - opponent_model_decode_observations: False
    - opponent_model_decode_rewards: False
    - opponent_model_decode_actions: True
    - latent_dims: 32
    - "--config": "mappo"
  
  env3:
    - "--env-config": "smaclite"
    - env_args.map_name: "corridor"
    - common_reward: True
    - t_max: 5050000
    - test_interval: 125000
    - log_interval: 100000
    - save_model_interval: 2500000
    - opponent_model_decode_observations: False
    - opponent_model_decode_rewards: False
    - opponent_model_decode_actions: True
    - latent_dims: 32
    - "--config": "mappo"