exclude: null
grid-search:

  save_model:
    - true

  opponent_modelling:
    - true
    - false


grid-search-groups:
  env0:
    - "--env-config": "gymma"
    - env_args.time_limit: 50
    - env_args.key: "lbforaging:Foraging-10x10-3p-3f-v3"
    - common_reward: False
    - t_max: 10050000
    - test_interval: 250000
    - log_interval: 100000
    - save_model_interval: 5000000
    - opponent_model_decode_observations: False
    - opponent_model_decode_actions: True
    - latent_dims: 32
    - "--config": "mappo"

  env1:
    - "--env-config": "gymma"
    - env_args.time_limit: 50
    - env_args.key: "lbforaging:Foraging-2s-10x10-3p-3f-v3"
    - common_reward: False
    - t_max: 10050000
    - test_interval: 250000
    - log_interval: 100000
    - save_model_interval: 5000000
    - opponent_model_decode_observations: False
    - opponent_model_decode_actions: True
    - latent_dims: 32
    - "--config": "mappo"

  env2:
    - "--env-config": "gymma"
    - env_args.time_limit: 50
    - env_args.key: "lbforaging:Foraging-10x10-3p-3f-v3"
    - common_reward: True
    - t_max: 10050000
    - test_interval: 250000
    - log_interval: 100000
    - save_model_interval: 5000000
    - opponent_model_decode_observations: False
    - opponent_model_decode_actions: True
    - latent_dims: 32
    - "--config": "mappo"

  env3:
    - "--env-config": "gymma"
    - env_args.time_limit: 25
    - env_args.key: "pz-mpe-simple-spread-v3"
    - common_reward: False
    - t_max: 10050000
    - test_interval: 250000
    - log_interval: 100000
    - save_model_interval: 5000000
    - opponent_model_decode_observations: False
    - opponent_model_decode_actions: True
    - latent_dims: 32
    - "--config": "mappo"

  env4:
    - "--env-config": "smaclite"
    - env_args.map_name: "2s3z"
    - common_reward: True
    - t_max: 5050000
    - test_interval: 125000
    - log_interval: 100000
    - save_model_interval: 2500000
    - opponent_model_decode_observations: False
    - opponent_model_decode_actions: True
    - latent_dims: 32
    - "--config": "mappo"